name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to EC2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-2'
        EC2_INSTANCE_ID: 'i-097bb48b9c8e1ca4f'
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "${SSH_PRIVATE_KEY}" > private_key.pem
        chmod 600 private_key.pem
        ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@ec2-3-146-35-43.us-east-2.compute.amazonaws.com << 'EOF'
          if [ ! -d "sample_test" ]; then
            git clone https://github.com/karamchandanideepak111/mytestrepo.git sample_test
          fi
          cd sample_test
          git stash
          git pull origin main
          git stash pop
          if [ ! -d "venv" ]; then
            python3 -m venv venv
          fi
          source venv/bin/activate
          pip install -r requirements.txt
          python3 manage.py migrate
          sudo fuser -k 8000/tcp
          nohup python3 manage.py runserver 0.0.0.0:8000 > server.log 2>&1 &
          disown
          exit
        EOF
